default:
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_KEY'] %>
  region: 'ap-northeast-1'
development:
  bucket: 'dev.octfilestorage'
  s3_host_name: 's3-ap-northeast-1.amazonaws.com'
test:
  bucket: test.octfilestorag
  s3_host_name: s3-ap-northeast-1.amazonaws.com
production:
  bucket: octfilestorage
  s3_host_name: s3-ap-northeast-1.amazonaws.com
